config/routes.rb
VisDir::Application.routes.draw do

  root :to => 'listings#index'
  
  resources :listings, :photographers
  
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  validates :name, presence: true
  validates :name, uniqueness: true
  
  has_many :listings
  has_many :photographers, through: :listings
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :ip_address
  
  has_many :favorites
  has_many :listings, through: :favorites
  
  def fav_count
    count = 0

    favorites.each { |f| count += 1 }

    count
  end
  
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :customer_id, :listing_id
  
  validates :customer_id, presence: true
  validates :listing_id, presence: true
  
  belongs_to :customer
  belongs_to :listing
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :budget, :category_id, :image, :location, :photographer_id, :photographer_attributes, :category_attributes
  
  belongs_to :photographer
  accepts_nested_attributes_for :photographer, :allow_destroy => true, :reject_if => :photographer_is_blank
  
  belongs_to :category
  accepts_nested_attributes_for :category, :allow_destroy => true, :reject_if => :category_is_blank
  
  has_many :favorites
  has_many :customers, through: :favorites
  
  validates :budget, presence: true
  validates :location, presence: true
  validates :category_id, presence: true
  
  scope :high_budget, where(:budget => "high")
  scope :low_budget, where(:budget => "low")
  
  mount_uploader :image, ImageUploader
  
  def category_is_blank(attrs)
    if attrs['name'].blank?
      true
    else
      false
    end
  end
  
  def photographer_is_blank(attrs)
    if attrs['name'].blank?
      true
    else
      false
    end
  end
  
end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
  attr_accessible :name, :pro_status, :email, :password, :password_confirmation
  
  has_many :listings
  has_many :categories, through: :listings
  
  validates :email, :password, :password_confirmation, presence: true
  # validates :email, uniqueness: true

  has_secure_password
  
  scope :pro_status?, where(:pro_status => true)
  scope :not_pro_status?, where(:pro_status => false)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # before_filter :authorize
  # before_filter :session_id
  #
  # def current_customer(customer)
  #   @customer = Customer.new(ip_address: session[:ip_address].to_s)
  #
  #   if @customer.save
  #     session[:customer_id] = @customer.id
  #   else
  #     customer = Customer.find(session[:customer_id])
  #     session[:customer_id] = customer.id
  #   end
  # end
  #
  # helper_method :current_customer
  #
  # # def authorize
  # #   if current_customer.nil?
  # #     redirect_to logins_path, :alert => "You need to log in to do that."
  # #   end
  # # end
  #
  # def session_id
  #   session[:ip_address] = request.remote_ip
  # end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  def index
    @listings = Listing.all
    @categories = Category.all
  end
  
  def new
    @listings = Listing.all
    @categories = Category.all
    @listing = Listing.new
  end
  
  def create
    @listing = Listing.new(params[:listing])
    
    if @listing.save
      redirect_to listing_path(@listing.id), :notice => "Creating listing."
    else
      render "new"
    end
  end
  
  def edit
    @listing = Listing.find(params[:id])
  end
  
  def update
    @listing = Listing.find(params[:id])
    
    if @listing.update_attributes(params[:listing])
      redirect_to listing_path(@listing.id), :notice => "Updating listing."
    else
      render "edit"
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
  end
  
  def destroy
    @listing = Listing.find(params[:id])
  end

end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController

  def index
    @photographers = Photographer.all
  end
  
  def new
    @photographer = Photographer.new
  end
  
  def create
    @photographer = Photographer.new(params[:photographer])
    
    if @photographer.save
      PhotographerMailer.delay(run_at: 1.minute.from_now).welcome(@photographer)
      redirect_to photographer_path(@photographer.id), :notice => "Your account has been created."
    else
      render "new"
    end
  end
  
  def edit
    @photographer = Photographer.find(params[:id])
  end
  
  def update
    @photographer = Photographer.find(params[:id])
    
    if @photographer.update_attributes(params[:photographer])
      redirect_to photographer_path(@photographer.id), :notice => "Your account has been updated."
    else
      render "edit"
    end
  end
  
  def show
    @photographer = Photographer.find(params[:id])
  end
  
  def destroy
    @photographer = Photographer.find(params[:id])
    PhotographerMailer.delay(run_at: 1.minute.from_now).delete(@photographer)
    @photographer.delete
    redirect_to photographers_path, :notice => "Your account has been deleted."
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/views/layouts/_searchbar.html.erb
<div id="searchbar">
  <div id="searchbar-label">I'm looking for</div>

  <div class="searchbar-section">
    <!-- #### HOW TO include the search for all categories ### -->
    <%= form_for :search do |f| %>
      <%= f.collection_select(:category_id, @categories, :id, :name )%>
    <% end %>
  
    <div class="searchbar-section-label">Photographers</div>
  </div>

  <div class="searchbar-label_section">in</div>

  <div class="searchbar-section">
    <%= form_for :search do |f| %>
      <%= f.collection_select(:location, @listings, :id, :location )%>
    <% end %>
    <!-- #### HOW TO include the search for all locations?? ### -->
  </div>

  <div class="searchbar-label_section">for</div>

  <div class="searchbar-section">
    <!-- #### HOW TO include the search for all budgets?? ### -->
    <%= form_for :search do |f| %>
      <%= f.collection_select(:budget, @listings, :id, :budget)%>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisDir</title>
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Roboto+Slab:700,400' type='text/css'>
  <link rel="stylesheet" href="css/application.css" type='text/css'>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="scripts/application.js"></script>
  <!-- DO NOT CHANGE THIS -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  
    <%= csrf_meta_tags %>
  <!--DO NOT CHANGE THIS -->
</head>
<body>

<%= session.inspect %>

<header>
  <div id="header">
    <h1 id="header-logo"><a href="#">VisDir</a></h1>
  
    <nav id="header-nav">
      <ul id="header-nav-ul">
        <li><a href="#" class="header-nav-link">Favs</a></li>
        <li><a href="#" class="header-nav-link">About</a></li>
      </ul>
    </nav>
  
    <div id="header-account">
      <div id="header-account-label">Photographers</div>
    
      <ul id="header-account-ul">
        <li id="header-account-login"><a href="#">Log in</a> or</li>
        <li id="header-account-signup"><a href="#">Sign up</a></li>
      </ul>
    </div>
  </div>
</header>

      <% if flash[:notice]%>
        <p id="notice"><%= flash[:notice]%></p>
        <% end %>
      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert]%></p>
      <% end %>

<%= yield %>

<footer>
  <div id="footer">
    <a href="#">VisDir</a>
  </div>
</footer>

</body>
</html>

app/views/listings/edit.html.erb
<h1>Edit <%= @listing.photographer.name %>'s details</h1>

<%= form_for @listing, :html => {:multipart => true } do |f| %>

  <p><%= f.label :budget %><br>
    <%= f.text_field :budget %></p>
  
  <p><%= f.label :location %></br>
    <%= f.text_field :location %></p>
  
  <p><%= f.label :image %></br>
  <%= f.file_field :image %></p>
  
  <!-- <%= f.label :remote_image_url, "or image URL" %>
  <%= f.text_field :remote_image_url %> -->
  
  <p>
    <%= f.fields_for :category do |c| %>
      <%= c.label :name, "Category" %></br>
      <%= c.text_field :name %>
    <% end %>

  
  <p><%= f.submit %></p>
<% end %>

app/views/listings/index.html.erb
<main>
  <div id="main">
    
    <%= render partial: "/layouts/searchbar" %>
  
    <div id="cards">
      
      <!-- Loop through all listings, -->
      <% @listings.each do |l| %>
      <!-- only display those where pro_status? => true-->
        <% if l.photographer.pro_status? %>
          <div class="card card-pro">
        
            <!-- ajax request to add this to current customer's faves -->
            <a href="#" class="card-fav">Add to Favs</a>
      
            <div class="card-preview">
          
              <!-- show associated image, make it clickable to the listing page -->
              <%= link_to(l.image, listing_path(l.id)) %>
              <a href="/listing/1"><img src="http://placekitten.com/220/200"></a>
            </div>
          
            <!-- list the associated photographer's name and link to the listing page -->
            <%= link_to(l.photographer.name, listing_path(l.id)) %>
            <!-- <h2 class="card-header"><a href="/listing/1">ACME Photography</a></h2> -->
      
            <div class="card-details">
            
              <!-- display each listing's locationand budget -->
              <div class="card-details-location"><%= l.location.capitalize %></div>
              <div class="card-details-budget"><%= l.budget.capitalize %> Budget</div>
            </div>
          </div>
          
        <% else %>
        <!-- only display those where pro_status? => false -->
        
        <div class="card">
          <a href="#" class="card-fav">Remove from Favs</a>
          
          <%= link_to(l.photographer.name, listing_path(l.id)) %>
          <!-- <h2 class="card-header"><a href="/listing/11">Still Photography</a></h2> -->
      
          <div class="card-preview">
            <%= link_to(l.image, listing_path(l.id)) %>
            <a href="/listing/11"><img src="http://placekitten.com/220/200"></a>
          </div>
      
          <div class="card-details">
            <div class="card-details-location"><%= l.location.capitalize %></div>
            <div class="card-details-budget"><%= l.budget.capitalize %> Budget</div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</main>

app/views/listings/new.html.erb
<h1>Create a new listing</h1>

<%= form_for @listing do |f| %>

  <p><%= f.label :budget %><br>
  <%= f.collection_select(:budget, @listings, :id, :budget) %><p>
  
  <p><%= f.label :location %></br>
  <%= f.collection_select(:location, @listings, :id, :location) %></p>
  
  <p><%= f.label :image %></br>
  <%= f.file_field :image %></p>
  
  <!-- <%= f.label :remote_image_url, "or image URL" %>
  <%= f.text_field :remote_image_url %> -->
  
  <p>
    <%= f.fields_for :category do |c| %>
      <%= c.label :name %></br>
      <%= c.collection_select(:category_id, @categories, :id, :name )%><p>
    <% end %>
  
  <!-- <%= f.label :category %>
  <%= f.collection_select(:category_id, @categories, :id, :name ) %> -->
  
  <p><%= f.submit %></p>
<% end %>

app/views/listings/show.html.erb
<h1><%= @listing.photographer.name %> details </h1>

<p><%= @listing.photographer.pro_status%></p>
<p><%= @listing.photographer.email%></p>
<p><%= @listing.budget%></p>
<p><%= @listing.location%></p>
<p><%= image_tag @listing.image_url.to_s %></p>
<p><%= @listing.category.name%></p>

<main>
  <div id="main">
    <h2 class="listing-details-header"><%= @listing.photographer.name %></h2>
    
    <div class="card card-full">
      <%= image_tag (@listing.image_url.to_s) %>
      <!-- <img src="http://placekitten.com/g/200/180"> -->
      
      <div class="listing-details">
        <h3 class="listing-details-subheader"><%= @listing.photographer.name %></h3>
        <div class="listing-details-location">Location: <%= @listing.location %></div>
        <div class="listing-details-budget"><%= @listing.budget.capitalize %> Budget</div>
        
        <p class="listing-details-description"><%= simple_format(@listing.description) %></p>
        
        <div class="listing-details-contact">
          <%= mail_to @listing.photographer.email %>
          <%= link_to("Homepage", @listing.photographer.homepage) %>
          <% if @listing.photographer.twitter != nil %>
            <%= link_to "Twitter", @listing.photographer.twitter %>
          <% end %>
          <!-- <% if @listing.photographer.twitter != nil %> -->
            
          <!-- <% end %> -->
          <!-- <a class="listing-details-contact-item" href="mailto:geoff_j@example.com">geoff_j@example.com</a>
          <a class="listing-details-contact-item" href="http://geoffjohnsonphoto.com">http://geoffjohnsonphoto.com</a> -->
          <!-- Optional: Link to Twitter account. (Some users will have one; others may not.) -->
        </div>
      </div>
    </div>
  </div>
</main>

app/views/photographers/edit.html.erb
<h1><%= @photographer.name %> - Edit</h1>

<%= form_for @photographer do |f| %>
  <p><%= f.label :name %></br>
  <%= f.text_field :name %></p>
  
  <p><%= f.label :email %></br>
  <%= f.text_field :email %></p>
  
  <p><%= f.label :password %></br>
  <%= f.password_field :password %></p>
  
  <p><%= f.label :password_confirmation %></br>
  <%= f.password_field :password_confirmation %></p>
  
  <p><%= f.label :pro_status %></br>
  <%= f.check_box :pro_status %></p>
  
  <p><%= f.submit %></p>
  
<% end %>

app/views/photographers/index.html.erb
<h1>All photographers on this site</h1>

<table>
  <tr>
    <td>Name</td>
    <td>Email</td>
    <td>Website</td>
    <td>Twitter</td>
    <td>Edit</td>
    <td>Destroy</td>
  </tr>
  <% @photographers.each do |p| %>
    <tr>
      <td><%= link_to(p.name, photographer_path(p.id)) %></td>
      <td><%= p.email %></td>
      <td>website tbd</td>
      <td>twitter tbd</td>
      <td><%= link_to("Edit", edit_photographer_path(p.id)) %></td>
      <td><%= link_to("Delete", photographer_path(p.id), method: :delete, data: { confirm: 'Are you sure?'} )%></td>
    </tr>
  <% end %>
</table>

app/views/photographers/new.html.erb
<h1>Create a new <%= @photographer.name %></h1>

<%= form_for @photographer do |f| %>
  <p><%= f.label :name %></br>
  <%= f.text_field :name %></p>
  
  <p><%= f.label :email %></br>
  <%= f.text_field :email %></p>
  
  <p><%= f.label :password %></br>
  <%= f.password_field :password %></p>
  
  <p><%= f.label :password_confirmation %></br>
  <%= f.password_field :password_confirmation %></p>
  
  <p><%= f.label :pro_status %></br>
  <%= f.check_box :pro_status %></p>
  
  <p><%= f.submit %></p>
  
<% end %>

app/views/photographers/show.html.erb
<h1><%= @photographer.name %></h1>

<p>
  Name: <%= @photographer.name %></br>
  Email: <%= @photographer.email %></br>
  Website: website tbd</br>
  Twitter: twitter tbd</br>
  Listings:</br>
    <% @photographer.listings.each do |l| %>
      Category: <%= l.category.name %></br>
      Budget: <%= l.budget %></br>
      Location: <%= l.location %>
    <% end %>
</p>